spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    username: u749392768_arthouse
    url: jdbc:mysql://srv622.hstgr.io:3306/u749392768_db_arthouse
    password: Meerrajeison1
    maxLifetime: 1800000 # Tempo máximo de vida da conexão em milissegundos (30 minutos)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
