spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/arthouse?useTimezone=true&serverTimezone=UTC
    password:
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue: org.hibernate.dialect.MySQL8Dialect
          storage_engine: innodb
        format_sql: true
    database-platform: org.hibernate.dialect
    hibernate:
      ddl-auto: update
    show-sql: true